name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          mvn deploy -s settings.xml -Dbuild=$(date +%Y%m%d-%H%M%S) -Dregistry=https://maven.pkg.github.com/wk-j
