name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: |
          mvn package -Dbuild=$(date +%Y%m%d-%H%M%S)
